services:
  frontend:
    container_name: frontend
    image: ${REGISTRY}/frontend:${TAG}
    restart: always
    networks:
      - d106-network
    volumes:
      - ${HOME}/d106/frontend/app/logs:/var/log/nginx
      - ${HOME}/deploy/frontend/conf.d:/etc/nginx/conf.d
    environment:
      TZ: "Asia/Seoul"

networks:
  d106-network:
    name: d106-network
    external: true