services:
  mariadb:
    image: mariadb:10.11.7
    container_name: backend-mariadb
    restart: always
    networks:
      - d106-network
    ports:
      - ${MARIADB_EXTERNAL_PORT}:${MARIADB_PORT}
    volumes:
      - ${HOME}/d106/mariadb/var/lib/mysql:/var/lib/mysql
    environment:
      TZ: "Asia/Seoul"
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    command: --character-set-server=utf8mb4  --collation-server=utf8mb4_bin
    
  redis:
    image: redis:7.2
    container_name: backend-redis
    restart: always
    networks:
      - d106-network
    ports:
      - ${REDIS_EXTERNAL_PORT}:${REDIS_PORT}
    volumes:
      - ${HOME}/d106/redis/data:/data
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      TZ: "Asia/Seoul"
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 512M  
    
  backend:
    image: ${REGISTRY}/backend:${TAG}
    container_name: backend
    restart: always
    networks:
      - d106-network
    volumes:
      - ${HOME}/d106/backend/app/logs:/app/logs
      - ${HOME}/d106/backend/app/files:/app/files
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: "Asia/Seoul"

networks:
  d106-network:
    name: d106-network
    external: true